name: 'Publish application'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v6

        # Install .NET SDK
        - name: Setup .NET 10
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: '10.0.x'
            
        # Added Ahead-Of-Time workload
        - name: Add AOT Workload
          run: |
            dotnet workload install wasm-tools
            dotnet workload restore

        # Generate the website
        - name: Publish
          run: dotnet publish src/Relewise.BlazorApps/Relewise.BlazorApps.csproj --configuration Release --output build

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: build/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
